title: Noah Sutherland # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Noah Sutherland Links:
  <br><br>
  <a href="https://www.linkedin.com/in/noahsutherland/">LinkedIn</a> 
  <br>
  <a href="https://github.com/ngs222?tab=repositories">GitHub</a>  
  <br>
  <a href="https://twitter.com/sutherland1noah?lang=en">Twitter</a>  
  
theme: jekyll-theme-minimal
